# Generated by Django 4.2 on 2023-04-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_userinfo_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address", name="zipcode", field=models.CharField(max_length=5),
        ),
    ]
